model:
  seq_len: 60
  pred_len: 30
  individual: False
  channels: 7

---
train:
  batch_size: 4
#  num_workers: 8 # num_workers does not work
  optimizer: 'adam'
  adam: 0.005
  summary_interval: 1
  checkpoint_interval: 50

---
data:
  trainset: 'dataset/ai_competition_train.csv'
  testset: 'dataset/ai_competition_test.csv'
  split_rate: 0.9

---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
