model:
  seq_len: 60
  pred_len: 30
  individual: False
  channels: 7

---
train:
  batch_size: 64
#  num_workers: 8 # num_workers does not work
  optimizer: 'adam'
  adam: 0.001
  summary_interval: 10
  checkpoint_interval: 500
  step_limit: 5000

---
data:
  trainset: 'dataset/ai_competition_train.csv'
  testset: 'dataset/ai_competition_test.csv'
  split_rate: 0.95

---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
