model:
  seq_len: 60
  label_len: 30
  pred_len: 30
  individual: False
  channels: 1
  moving_avg: 15
  output_attention: False
  enc_in: 1
  dec_in: 1
  c_out: 1
  d_model: 512
  embed: timeF  # options:[timeF, fixed, learned]
  freq: d  # [s:secondly, t:minutely, h:hourly, d:daily, b:business days, w:weekly, m:monthly]
  dropout: 0.0  # default = 0.05
  factor: 1
  n_heads: 8
  n_hashes: 4
  bucket_size: 4
  d_ff: 2048
  activation: gelu
  e_layers: 2
  d_layers: 1
  features: M
  distil: True
---
train:
  batch_size: 512
  num_workers: 0 # num_workers does not work
  optimizer: 'adam'
  adam: 0.00001
  summary_interval: 250
  checkpoint_interval: 1000
  step_limit: 15000

---
data:
  trainset: 'dataset/ai_competition_train.csv'
  testset: 'dataset/ai_competition_test.csv'
  split_rate: 0.9

---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
