model:
  seq_len: 60
  pred_len: 30
  individual: True
  channels: 1

---
train:
  batch_size: 1024
  num_workers: 0 # num_workers does not work
  optimizer: 'adam'
  adam: 0.0001
  summary_interval: 250
  checkpoint_interval: 1000
  step_limit: 15000

---
data:
  trainset: 'dataset/ai_competition_train.csv'
  testset: 'dataset/ai_competition_test.csv'
  split_rate: 0.95

---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
