model:
  seq_len: 60
  label_len: 30
  pred_len: 30
  individual: False
  channels: 1
  moving_avg: 15
  output_attention: False
  enc_in: 1
  dec_in: 1
  c_out: 1
  d_model: 256
  embed: timeF  # options:[timeF, fixed, learned]
  freq: d  # [s:secondly, t:minutely, h:hourly, d:daily, b:business days, w:weekly, m:monthly]
  dropout: 0.025  # default = 0.05
  factor: 1
  n_heads: 8
  d_ff: 2048
  activation: relu
  e_layers: 2
  d_layers: 1
  features: M
---
train:
  batch_size: 256
  num_workers: 0 # num_workers does not work
  optimizer: 'adam'
  adam: 0.0001
  summary_interval: 10
  checkpoint_interval: 100
  step_limit: 30000

---
data:
  trainset: 'dataset/ai_competition_train.csv'
  testset: 'dataset/ai_competition_test.csv'
  split_rate: 0.95

---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
